### ISSUE TITLE
Plugin highlights valid Yang files as invalid

### ISSUE THREAD

**Issue by palko08** [PANTHEONtech/YANGinator#11]
![yanginatorBug](https://user-images.githubusercontent.com/48720188/140025871-fd7af342-0c7a-4f44-a2a1-8054d219eced.png)

**Comment by matusbabinsky** [comment]
validation is currenly based on rfc6020

![image](https://user-images.githubusercontent.com/90239536/140027423-763385e4-927b-4db3-94be-4c11c6a49aa4.png)

import is part of linkage-stmts so it should be before organization-stmt that is part of met-stmts

**Comment by SamoSchneider** [comment]
@palko08 
Validation is currenly based on rfc6020 https://datatracker.ietf.org/doc/html/rfc6020#section-12.
Import is part of linkage-stmts so it should be before organization-stmt that is part of meta-stmts.
