### ISSUE TITLE
Syntax highlighter highlights keywords in the multi-line comments

### ISSUE THREAD

**Issue by IvanMartiniak** [PANTHEONtech/YANGinator#125]
The Image speaks for itself.

![hhhhhhhhhhhh](https://user-images.githubusercontent.com/73988333/180367646-7dab9426-27df-4cf4-9034-5b1348eca42b.png)

The interesting part is, that the issue does not appear the same for every keyword. See **typedef typedef, module, module.** 

A keyword **typedef** is wrongly highlighted when it is followed by whitespace, but when it is followed by a colon, highlighting is correct. 

On the other hand, the keyword **module** can be followed by whitespace or colon, highlighting is wrong every time.

**Comment by Simonito** [comment]
Do I understand correctly that your concern is that keywords are highlighted despite the fact that they are inside of a block comment?

**Comment by IvanMartiniak** [comment]
Correctly.  Every word or character inside the block comment (or single-line comment) must be highlighted by the proper comment color (grey in this case).
