### ISSUE TITLE
Missing documentation in the ModelDeviations.md for other modifications

### ISSUE THREAD

**Issue by Simonito** [PANTHEONtech/YANGinator#137]
The changes are briefly documented in the code as a Javadoc-type comment. These actions should be explained also in the ModelDeviations.md file [here](https://github.com/PANTHEONtech/YANGinator/blob/master/rfc-parser/docs/ModelDeviations.md)

~(If the link results in Page Not Found error, the changes weren't merged -> try [clicking here](https://github.com/PANTHEONtech/YANGinator/blob/bugfix-134/rfc-parser/docs/ModelDeviations.md) instead)~ _(deprecated)_

**Comment by fk00750** [comment]
Both were not found

**Comment by Simonito** [comment]
It should work now
