### ISSUE TITLE
Augment with more augment-arg-str dont work properly.

### ISSUE THREAD

**Issue by peterivanic** [PANTHEONtech/YANGinator#160]
![image](https://user-images.githubusercontent.com/60007423/215434380-204c93de-1873-4fba-b893-9fbb2b4dae08.png)

**Comment by Filip-Vitkovsky** [comment]
![Screenshot from 2023-01-30 10-50-48](https://user-images.githubusercontent.com/37344322/215444379-f43e6835-3a61-48c8-b9c7-ae908c1f63e8.png)
If every added string follows the RFC6020/7950 rules for absolute-schema-nodeid and/or descendant-schema-nodeid then there is no error. Possible fix may be to add a multi string stmt.
