### ISSUE TITLE
Comment syntax error

### ISSUE THREAD

**Issue by Filip-Vitkovsky** [PANTHEONtech/YANGinator#226]
"\\" is the problem

file:
[ieee1906-dot1-types.txt](https://github.com/PANTHEONtech/YANGinator/files/10881942/ieee1906-dot1-types.txt)

**Comment by peterivanic** [comment]
![image](https://user-images.githubusercontent.com/60007423/222772301-c2d175ef-d934-4ee2-b2ef-ea0d7553eeda.png)
![image](https://user-images.githubusercontent.com/60007423/222773209-9d9858b7-b9ca-40f9-8a0e-f38eff378915.png)
