### ISSUE TITLE
Review/Rework plugin based on best practices from Gradle PoV

### ISSUE THREAD

**Issue by PetkoNosal** [PANTHEONtech/YANGinator#62]
- [x] Make sure that all *.gradle files are structured and set up based on best gradle practices
- [x] Make sure that all versions are up to date and properly defined (dependency management)

**Comment by vbacinsky** [comment]
all *.gradle files are structured based on 
https://plugins.jetbrains.com/docs/intellij/gradle-prerequisites.html#components-of-a-wizard-generated-gradle-intellij-platform-plugin

and added gradle.properties file
