### ISSUE TITLE
Review/Rework plugin based on best practices from Jetbrains Plugin PoV

### ISSUE THREAD

**Issue by PetkoNosal** [PANTHEONtech/YANGinator#63]
- [x] Make sure that structure of plugin is how it should be according to Jetbrains Plugin documentation
- [x] Make sure that all files and definitions are how they should be according to Jetbrains Plugin documentation
- [x] Make sure that everything in plugin.xml is set up how it should be according to Jetbrains Plugin documentation

- [x] Leverage PatchPluginXml task in build.gradle (add there everything that is currently manually changed in plugin.xml)
- [x] Change supported jetbrains platforms from IDEA only to everything possible

**Comment by vbacinsky** [comment]
Added link on github and version in plugin.xml based on:
https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html

here
https://plugins.jetbrains.com/docs/intellij/gradle-guide.html#verifying-plugin
you can find this sentence
"if you modify project.version in build.gradle, the Gradle plugin will automatically update the <version> value in the plugin.xml "
